name: Actions Workshow Testing

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  issues:
    types: [opened, edited]

jobs:
  experimental-great:
    env:
      MY_ENV: "John Doe"
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User
        run: echo "Hello World!"
      - name: Show directory before checkout
        run: ls -l
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Show directory after checkout
        run: ls -l
      - name: Run a multi-line script
        run: |
          echo "Hello $MY_ENV"
          echo "Hello $GITHUB_ACTOR"
